---

- name: Disable Enterprise Repo if exists
  lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb'
    state: absent
  ignore_errors: true

- name: Backup Current Config (safe for any version)
  shell: |
    mkdir -p /root/backup-pve-config
    cp -a /etc/apt /root/backup-pve-config/
    cp -a /etc/pve /root/backup-pve-config/

- name: Configure Debian 12 Bookworm Sources
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://deb.debian.org/debian bookworm main contrib
      deb http://deb.debian.org/debian bookworm-updates main contrib
      deb http://security.debian.org/debian-security bookworm-security main contrib

- name: Configure PVE 8 No-Subscription Repo
  copy:
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    content: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

- name: Install Bookworm Keyring (safe to re-run)
  apt:
    name: debian-archive-keyring
    state: present
    update_cache: yes

- name: Perform Full System Upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: Cleanup Unused Packages
  apt:
    autoremove: yes
    purge: yes

- name: Notify Manual Reboot
  debug:
    msg: "Proxmox VE system upgraded — please reboot manually."
