- name: Check if template VM already exists
  stat:
    path: "/etc/pve/qemu-server/{{ template_vm_id }}.conf"
  register: template_vm_stat

- name: Skip if template already exists
  debug:
    msg: "Template VM {{ template_vm_id }} already exists. Skipping creation."
  when: template_vm_stat.stat.exists

- name: Create cloud-init template VM
  block:

    - name: Ensure image and snippet directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "/var/lib/vz/template"
        - "/var/lib/vz/snippets"
      delegate_to: "{{ template_node }}"

    - name: Download official Ubuntu cloud image (.qcow2)
      get_url:
        url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
        dest: "/var/lib/vz/template/jammy-server-cloudimg-amd64.qcow2"
        mode: '0644'
        force: yes
      delegate_to: "{{ template_node }}"

    - name: Convert qcow2 image to raw for ZFS
      command: >
        qemu-img convert -f qcow2 -O raw
        /var/lib/vz/template/jammy-server-cloudimg-amd64.qcow2
        /var/lib/vz/template/jammy-server-cloudimg-amd64.raw
      args:
        creates: "/var/lib/vz/template/jammy-server-cloudimg-amd64.raw"
      delegate_to: "{{ template_node }}"

    - name: Resize raw image disk
      command: >
        qemu-img resize /var/lib/vz/template/jammy-server-cloudimg-amd64.raw {{ template_disk_size }}
      delegate_to: "{{ template_node }}"

    - name: Copy cloud-init user-data
      template:
        src: "files/user-data.yml.j2"
        dest: "/var/lib/vz/snippets/user-data.yml"
      delegate_to: "{{ template_node }}"

    - name: Create base VM
      command: >
        qm create {{ template_vm_id }}
        --name {{ template_vm_name }}
        --memory {{ template_memory }}
        --cores {{ template_cores }}
        --sockets {{ template_sockets }}
        --net0 virtio,bridge={{ template_net_bridge }}
        --agent 1
        --ostype l26
        --scsihw virtio-scsi-single
        --serial0 socket
        --vga serial0
      delegate_to: "{{ template_node }}"

    - name: Import raw disk into Proxmox (ZFS)
      command: >
        qm importdisk {{ template_vm_id }} /var/lib/vz/template/jammy-server-cloudimg-amd64.raw {{ template_storage }}
      delegate_to: "{{ template_node }}"

    - name: Final VM configuration
      command: >
        qm set {{ template_vm_id }}
        --scsi0 {{ template_storage }}:vm-{{ template_vm_id }}-disk-0,ssd=1,discard=on
        --ide2 {{ template_storage }}:cloudinit
        --boot order=scsi0;ide2;net0
        --cicustom "user=local:snippets/user-data.yml"
        --ipconfig0 ip=dhcp
      delegate_to: "{{ template_node }}"

    - name: Convert VM to template
      command: >
        qm template {{ template_vm_id }}
      delegate_to: "{{ template_node }}"

  when: not template_vm_stat.stat.exists