---
# roles/print-server/tasks/main.yml

- name: Include hostname setup
  import_tasks: hostname.yml
  tags: [cups, setup]

- name: Include package installation
  import_tasks: install.yml
  tags: [cups, install]

- name: Include service management
  import_tasks: service.yml
  tags: [cups, service]

- name: Include CUPS configuration
  import_tasks: config.yml
  tags: [cups, config]

- name: Include printer driver tasks
  import_tasks: driver.yml
  tags: [cups, driver]

- name: Include printer setup tasks
  import_tasks: printer.yml
  tags: [cups, printer]

- name: Include fallback user creation
  import_tasks: users.yml
  tags: [cups, users]
