- name: Install CUPS and required packages
  apt:
    name:
      - cups
    state: present
    update_cache: yes

- name: Enable and start CUPS service
  systemd:
    name: cups
    enabled: true
    state: started

- name: Configure CUPS daemon settings
  template:
    src: cups/cupsd.conf.j2
    dest: /etc/cups/cupsd.conf
    mode: '0644'
  notify: Restart CUPS

- name: Download Epson ESC/P-R driver (ET-2850)
  get_url:
    url: "https://download3.epson.biz/pub/epson/inkjet/escpr/debian/epson-inkjet-printer-escpr_1.8.6-1_amd64.deb"
    dest: "/tmp/epson-escpr.deb"
    mode: '0644'

- name: Install Epson ESC/P-R driver
  apt:
    deb: "/tmp/epson-escpr.deb"

- name: Add Epson ET-2850 printer using ESC/P-R model
  command: >
    lpadmin -p Epson_ET2850
    -E
    -v usb://EPSON/ET-2850_Series
    -m epson-inkjet-printer-escpr:Epson-ET-2850_Series-epson-driver.ppd
  args:
    creates: /etc/cups/ppd/Epson_ET2850.ppd

- name: Set Epson ET-2850 as default printer
  command: lpadmin -d Epson_ET2850

- name: Set Epson ET-2850 as default printer
  command: lpadmin -d Epson_ET2850

- name: Set printer default options (PageSize, Duplex, ColorModel)
  command: >
    lpadmin -p Epson_ET2850
    -o PageSize=A4
    -o Duplex=DuplexNoTumble
    -o ColorModel=Gray

- name: Set system-wide default user options for Epson ET-2850
  command: >
    lpoptions -p Epson_ET2850
    -o PageSize=A4
    -o Duplex=DuplexNoTumble
    -o ColorModel=Gray
