- name: Ensure RustDesk root dir exists
  become: true
  file:
    path: "{{ veloren_root }}/data"
    state: directory
    mode: '0755'

- name: Deploy docker-compose.yml
  become: true
  template:
    src: veloren-docker-compose.yml.j2
    dest: "{{ veloren_root }}/docker-compose.yml"
    mode: '0644'

- name: Bring up Veloren stack
  become: true
  command: bash -lc "cd {{ veloren_root }} && docker compose up -d"

