#/roles/upgrade/tasks/configure_sources.yml
---
- name: Configure Debian 12 Bookworm Sources
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://deb.debian.org/debian bookworm main contrib
      deb http://deb.debian.org/debian bookworm-updates main contrib
      deb http://security.debian.org/debian-security bookworm-security main contrib
  tags: [configure_sources]
- name: Configure PVE 8 No-Subscription Repo
  copy:
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    content: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
  tags: [configure_sources]
