---
- name: Copy the latest Proxmox VE ISO to Proxmox Server
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Read Proxmox server IP and details from ip.yml
      set_fact:
        pve_config: "{{ lookup('file', 'ip.yml') | from_yaml }}"

    - name: Print Proxmox server details
      debug:
        msg: "Proxmox server details: {{ pve_config.server }}"

    - name: Get the Proxmox server IP address
      set_fact:
        pve_ip: "{{ pve_config.server.pve_ip }}"

    - name: Ensure log file exists
      ansible.builtin.file:
        path: /var/log/usr_logs
        state: touch
        mode: '0644'
    
    - name: Find all ISO files
      ansible.builtin.find:
        paths: /rpool1/share/Common/Softwares/ISO files
        patterns: "*.iso"
        recurse: no
        file_type: file
      register: iso_files

    - name: Fail if no ISO file is found
      ansible.builtin.fail:
        msg: "No ISO files found in the specified directory!"
      when: iso_files.matched == 0

    - name: Log error if no ISO found
      ansible.builtin.lineinfile:
        path: /var/log/usr_logs
        line: "{{ ansible_date_time.iso8601 }} - ERROR: No ISO files found!"
        create: yes
      when: iso_files.matched == 0

    - name: Check if the latest ISO already exists on Proxmox
      ansible.builtin.stat:
        path: "/var/lib/vz/template/iso/{{ iso_files.files[0].path | basename }}"
      delegate_to: "{{ pve_ip }}"
      register: existing_iso

    - name: Copy the latest ISO file to the Proxmox server
      ansible.builtin.copy:
        src: "{{ iso_files.files[0].path }}"
        dest: "/var/lib/vz/template/iso/"
        owner: root
        group: root
        mode: '0644'
      delegate_to: "{{ pve_ip }}"
      when: not existing_iso.stat.exists
      register: copy_result
      ignore_errors: yes  # Prevent playbook from stopping on error

    - name: Log success or failure
      ansible.builtin.lineinfile:
        path: /var/log/usr_logs
        line: "{{ ansible_date_time.iso8601 }} - {{ 'SUCCESS: ISO copied' if copy_result is succeeded else 'ERROR: Failed to copy ISO' }}"
        create: yes
      when: not existing_iso.stat.exists

    - name: Notify if the ISO already exists
      ansible.builtin.debug:
        msg: "The latest ISO {{ iso_files.files[0].path | basename }} is already present on Proxmox. Skipping copy."
      when: existing_iso.stat.exists

    - name: Log if ISO already exists
      ansible.builtin.lineinfile:
        path: /var/log/usr_logs
        line: "{{ ansible_date_time.iso8601 }} - INFO: ISO {{ iso_files.files[0].path | basename }} already exists on Proxmox."
        create: yes
      when: existing_iso.stat.exists
      
    - name: Log success or failure
      ansible.builtin.debug:
        msg: "Ansible task completed successfully on {{ ansible_date_time.iso8601 }}"
