---
# roles/proxmox-usb/tasks/main.yml
# USB passthrough for Epson ET-2850 to target VM

- name: Ensure Epson ET-2850 is passed through to print VM
  command: "qm set {{ print_server_vm_id }} -usb0 host=04b8:118b"
  become: true
  when: ansible_hostname == 'pve'
  tags: [cups, usb, et2850, proxmox]
