#roles/create-vm-desktop/tasks/create-vm-from-template.yml
---
- name: Clone template VM
  command: >
    qm clone {{ desktop_template_id }} {{ desktop_vm_id }}
    --name {{ desktop_vm_name }}
  args:
    creates: "/etc/pve/qemu-server/{{ desktop_vm_id }}.conf"

- name: Resize disk of new VM
  command: >
    qm resize {{ desktop_vm_id }} scsi0 {{ desktop_vm_disk_size }}
  when: desktop_vm_disk_size is defined

- name: Set CPU cores
  command: >
    qm set {{ desktop_vm_id }} --cores {{ desktop_vm_cores }}

- name: Set memory
  command: >
    qm set {{ desktop_vm_id }} --memory {{ desktop_vm_memory }}

- name: Set network bridge
  command: >
    qm set {{ desktop_vm_id }} --net0 virtio,bridge={{ desktop_vm_net_bridge }}

- name: Set static IP config via cloud-init
  command: >
    qm set {{ desktop_vm_id }} --ipconfig0 ip={{ desktop_vm_ip }},gw={{ desktop_vm_gateway }}
  when: desktop_vm_ip is defined and desktop_vm_gateway is defined

- name: Enable autostart for VM
  command: qm set {{ desktop_vm_id }} --onboot 1

- name: Set boot order
  command: qm set {{ desktop_vm_id }} --boot order=scsi0

