---
# playbooks/validate-file-server.yml

- name: Validate NFS exports on Proxmox host
  hosts: pve-main
  become: yes
  tasks:
    - name: Check NFS exports
      command: exportfs -v
      register: nfs_exports

    - name: Assert expected NFS paths are exported
      assert:
        that:
          - "'/tankmirror/share' in nfs_exports.stdout"
          - "'/tankmirror/backup' in nfs_exports.stdout"


- name: Validate NFS mount and Samba service on Samba VM
  hosts: samba-server
  become: yes
  tasks:
    - name: Check if /mnt/share is mounted
      ansible.builtin.shell: mount | grep '/mnt/share'
      register: share_mount_check
      ignore_errors: true
      changed_when: false

    - name: Warn if /mnt/share is not mounted
      ansible.builtin.debug:
        msg: "/mnt/share is NOT mounted."
      when: share_mount_check.rc != 0

    - name: Fail if /mnt/share is not mounted
      ansible.builtin.fail:
        msg: "/mnt/share is missing — NFS mount likely failed."
      when: share_mount_check.rc != 0

    - name: Debug mount status
      debug:
        var: share_mount_check.stdout

    - name: Gather service facts
      service_facts:

    - name: Ensure smbd service is active
      assert:
        that:
          - ansible_facts.services['smbd.service'].state == "running"
        fail_msg: "Samba (smbd) is not running on the Samba VM"
        success_msg: "Samba (smbd) is running correctly on the Samba VM"
