---
- name: Install fail2ban (if enabled)
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: yes
  when: fail2ban_enabled

- name: Ensure SSH server is installed
  ansible.builtin.apt:
    name: "{{ ssh_server_package }}"
    state: present

- name: Harden SSH configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    create: true
    backrefs: true
  loop: "{{ harden_ssh_settings }}"
  notify: Restart SSH service

- name: Install unattended-upgrades (if enabled)
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
    update_cache: yes
  when: unattended_upgrades_enabled

- name: Enable automatic updates (if enabled)
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
    owner: root
    group: root
    mode: '0644'
  when: unattended_upgrades_enabled

- name: Configure unattended-upgrades for security only
  copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Allowed-Origins {
          "${distro_id}:${distro_codename}-security";
      };
      Unattended-Upgrade::Automatic-Reboot "true";
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
    owner: root
    group: root
    mode: '0644'

- name: Set fallback root password only if it is unset or disabled
  ansible.builtin.shell: |
    if grep -q '^root:[*!]:' /etc/shadow; then
      echo 'root:{{ fallback_root_password }}' | chpasswd && echo "Password set."
    else
      echo "Root password already set. Skipping."
    fi
  args:
    executable: /bin/bash
  when: fallback_root_password is defined
  register: root_pw_output

- name: Show root password set result
  ansible.builtin.debug:
    var: root_pw_output.stdout_lines
  when: fallback_root_password is defined


- name: Enable TTY1 console login for fallback access
  ansible.builtin.systemd:
    name: getty@tty1.service
    enabled: true
    state: started