- include_tasks: fail2ban.yml

- include_tasks: harden-ssh.yml

- include_tasks: install-unattended-upgrades.yml
  when: unattended_upgrades_enabled | bool

- include_tasks: automatic-updates.yml
  when: unattended_upgrades_enabled | bool

- include_tasks: enable-timers.yml
  when: unattended_upgrades_enabled | bool
