- name: Bootstrap Basrc (test source ~/.bashrc)
  include_tasks: bashrc.yml

# - name: Ensure Vault password file exists
#   include_tasks: vault-pass.yml

# - name: Install Packages For Ansible to Work!
#   include_tasks: install-packages.yml

# - name: Fix SSS permission
#   include_tasks: verify-ssh-permission.yml