- name: Ensure ~/.ssh directory exists
  file:
    path: "{{ lookup('env','HOME') }}/.ssh"
    state: directory
    mode: "0700"

- name: Fix permissions for authorized_keys if present
  file:
    path: "{{ lookup('env','HOME') }}/.ssh/authorized_keys"
    state: file
    mode: "0600"
  ignore_errors: true

- name: Fix permissions for private keys in ~/.ssh
  file:
    path: "{{ item }}"
    mode: "0600"
  loop: "{{ lookup('fileglob', lookup('env','HOME') + '/.ssh/id_*', wantlist=True) }}"
  when: item is match(".*[^.]$")   # avoids pub files
  ignore_errors: true

- name: Fix permissions for public keys in ~/.ssh
  file:
    path: "{{ item }}"
    mode: "0644"
  loop: "{{ lookup('fileglob', lookup('env','HOME') + '/.ssh/id_*.pub', wantlist=True) }}"
  ignore_errors: true
