#roles/hibernate/tasks/main.yml

- name: Deploy nightly shutdown script (11PM–wake at 5PM) with logging
  copy:
    dest: /usr/local/bin/shutdown-overnight.sh
    mode: '0755'
    owner: root
    group: root
    content: |
      #!/bin/bash

      LOG_FILE="/var/log/shutdown-wake.log"
      WAKE_HOURS=16  # Wake in XX hours (11PM → 5PM next day)

      echo "[$(date)] Starting shutdown + RTC wake cycle" >> "$LOG_FILE"

      echo "[$(date)] Scheduling RTC wake in ${WAKE_HOURS} hours..." >> "$LOG_FILE"
      rtcwake -m no -s $((WAKE_HOURS * 3600)) >> "$LOG_FILE" 2>&1

      echo "[$(date)] System shutting down" >> "$LOG_FILE"
      shutdown -h now "Scheduled wakeup in ${WAKE_HOURS} hours"



- name: Schedule hibernation at 11PM every day (wake at 5PM)
  cron:
    name: "Hibernate Daily 11PM–5PM"
    minute: "0"
    hour: "23"
    user: root
    job: "/usr/local/bin/hibernate-overnight.sh"

