#/roles/upgrade/tasks/configure_sources.yml
---
- name: Configure Debian 13 Trixie Sources
  copy:
    dest: /etc/apt/sources.list
    content: |
      deb http://deb.debian.org/debian trixie main contrib non-free-firmware
      deb http://deb.debian.org/debian trixie-updates main contrib non-free-firmware
      deb http://security.debian.org/debian-security trixie-security main contrib non-free-firmware
  tags: [configure_sources]

# - name: Configure PVE 9 No-Subscription Repo
#   copy:
#     dest: /etc/apt/sources.list.d/pve-no-subscription.list
#     content: |
#       deb http://download.proxmox.com/debian/pve trixie pve-no-subscription
#   tags: [configure_sources]
