# tasks file for ansible/roles/create-workstation-ubuntu/tasks/install-brave.yml
- name: Download Brave keyring to /usr/share/keyrings via curl
  shell: curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/brave-browser-archive-keyring.gpg

- name: Download Brave APT source file (.sources format) via curl
  shell: curl -fsSLo /etc/apt/sources.list.d/brave-browser-release.sources https://brave-browser-apt-release.s3.brave.com/brave-browser-release.sources
  args:
    creates: /etc/apt/sources.list.d/brave-browser-release.sources

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Brave browser
  apt:
    name: brave-browser
    state: present
