- name: Check if rtcwake exists
  ansible.builtin.command: which rtcwake
  register: rtcwake_path
  changed_when: false
  failed_when: rtcwake_path.rc != 0
  tags: validate

- name: Check if system supports hibernation
  ansible.builtin.command: "systemctl hibernate --dry-run"
  register: hibernate_check
  changed_when: false
  failed_when: hibernate_check.rc != 0
  tags: validate

- name: Check if RTC wake is possible (requires root)
  ansible.builtin.command: "rtcwake -m show"
  register: rtc_mode
  changed_when: false
  failed_when: "'disk' not in rtc_mode.stdout"
  tags: validate

- name: ✅ Hibernate + rtcwake are supported
  ansible.builtin.debug:
    msg: "PASS: rtcwake is available and hibernate is supported on this system."
  tags: validate
