# tasks file for install-edge

- name: Download and dearmor Microsoft GPG key on remote
  shell: >
    curl -fsSL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor -o /tmp/microsoft.gpg
  args:
    creates: /tmp/microsoft.gpg

- name: Move Microsoft GPG key to trusted.gpg.d
  copy:
    src: /tmp/microsoft.gpg
    dest: /etc/apt/trusted.gpg.d/microsoft.gpg
    owner: root
    group: root
    mode: '0644'
    remote_src: true

- name: Add Microsoft Edge APT repository
  copy:
    dest: "{{ edge_repo_file }}"
    content: |
      deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main
    owner: root
    group: root
    mode: '0644'

- name: Remove duplicate Microsoft Edge sources if present
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apt/sources.list.d/microsoft-edge-dev.list
    - /etc/apt/sources.list.d/microsoft-edge.list
  when: item != edge_repo_file

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Microsoft Edge
  apt:
    name: microsoft-edge-stable
    state: present
