# tasks file for ansible/roles/create-vm-desktop/


- name: Install Ubuntu Desktop Environment
  apt:
    name: ubuntu-desktop
    state: present
    update_cache: true

- name: Install additional GUI tools
  apt:
    name:
      - firefox
      - gnome-terminal
      - nautilus
      - gedit
    state: present

- name: Set systemd default target to graphical
  file:
    src: /lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
    force: true
