# roles/create-vm-desktop/tasks/remote-desktop.yml

- name: Ensure reboot after desktop install
  reboot:
    msg: "Rebooting after installing Ubuntu desktop environment and Brave browser"
    pre_reboot_delay: 10
    reboot_timeout: 300